import type { GlobalConfig } from "payload";
import { manageCmsContent } from "../access/cmsUsers";

export const GlobalSEO: GlobalConfig = {
  slug: "global-seo",
  label: "Global SEO",
  admin: { group: "Marketing and SEO", description: "Site-wide search and sharing defaults. Verified organization details generate Organization and WebSite JSON-LD automatically; page records can override page-specific metadata." },
  access: { read: () => true, update: manageCmsContent },
  fields: [
    { type: "tabs", tabs: [
      { label: "Search defaults", fields: [
        { name: "siteURL", label: "Canonical site origin", type: "text", defaultValue: "https://startime.sa", admin: { description: "HTTPS origin only, without a trailing slash. Local previews never use localhost as a canonical URL." } },
        { name: "siteName", type: "text", localized: true, defaultValue: "Startime" },
        { name: "titleTemplate", label: "Page title template", type: "text", localized: true, defaultValue: "%s | Startime", admin: { description: "Use %s where the page title should appear." } },
        { name: "defaultTitle", type: "text", localized: true },
        { name: "defaultDescription", type: "textarea", localized: true },
        { name: "defaultKeywords", label: "Accurate search topics", type: "array", localized: true, fields: [{ name: "keyword", type: "text", required: true }] },
        { name: "allowSearchIndexing", label: "Allow public search indexing", type: "checkbox", defaultValue: false, admin: { description: "Keep off during review. STAGING_NOINDEX still overrides this setting on staging." } },
        { name: "followLinks", type: "checkbox", defaultValue: true },
        { name: "noArchive", type: "checkbox", defaultValue: false },
        { name: "noImageIndex", type: "checkbox", defaultValue: false },
        { name: "maxSnippet", label: "Maximum snippet length (-1 = unrestricted)", type: "number", min: -1 },
        { name: "maxImagePreview", type: "select", options: ["none", "standard", "large"], defaultValue: "large" },
        { name: "maxVideoPreview", label: "Maximum video preview seconds (-1 = unrestricted)", type: "number", min: -1 },
        { name: "includeHreflang", label: "Generate English/Arabic hreflang", type: "checkbox", defaultValue: true },
        { name: "includeXDefault", label: "Generate x-default pointing to English", type: "checkbox", defaultValue: true },
      ] },
      { label: "Social sharing", fields: [
        { name: "openGraphTitle", type: "text", localized: true },
        { name: "openGraphDescription", type: "textarea", localized: true },
        { name: "openGraphImage", label: "Default Open Graph image", type: "upload", relationTo: "media", admin: { description: "Recommended 1200 × 630 px (1.91:1), WebP or JPG. Pages may override this image." } },
        { name: "openGraphImageAlt", type: "text", localized: true },
        { name: "twitterCard", type: "select", defaultValue: "summary_large_image", options: ["summary", "summary_large_image"] },
        { name: "twitterSite", label: "X account handle", type: "text", admin: { description: "For example @Startime; leave blank if unverified." } },
        { name: "twitterCreator", label: "X creator handle", type: "text" },
        { name: "twitterImage", label: "X-specific image (optional)", type: "upload", relationTo: "media", admin: { description: "Recommended 1200 × 675 px; falls back to the Open Graph image." } },
      ] },
      { label: "Organization schema", fields: [
        { name: "enableOrganizationSchema", type: "checkbox", defaultValue: true },
        { name: "organizationName", type: "text", localized: true },
        { name: "legalName", type: "text", localized: true },
        { name: "alternateName", type: "text", localized: true },
        { name: "organizationDescription", type: "textarea", localized: true },
        { name: "organizationLogo", type: "upload", relationTo: "media", admin: { description: "Official transparent logo; recommended 600 × 600 px or vector SVG." } },
        { name: "foundingDate", type: "text", admin: { description: "Only enter a verified ISO date, e.g. 2009-01-01. Do not infer from a timeline year." } },
        { name: "organizationPhone", type: "text" },
        { name: "organizationEmail", type: "email" },
        { name: "sameAs", label: "Verified official profile URLs", type: "array", fields: [{ name: "url", type: "text", required: true }] },
        { name: "areasServed", type: "array", fields: [{ name: "name", type: "text", required: true }] },
        { name: "knowsAbout", label: "Verified areas of expertise", type: "array", localized: true, fields: [{ name: "topic", type: "text", required: true }] },
        { name: "streetAddress", type: "text", localized: true },
        { name: "addressLocality", type: "text", localized: true },
        { name: "addressRegion", type: "text", localized: true },
        { name: "postalCode", type: "text" },
        { name: "addressCountry", type: "text", defaultValue: "SA" },
        { name: "latitude", type: "number", min: -90, max: 90 },
        { name: "longitude", type: "number", min: -180, max: 180 },
        { name: "contactType", type: "text", localized: true, defaultValue: "customer service" },
      ] },
      { label: "Automatic structured data", fields: [
        { name: "enableWebsiteSchema", type: "checkbox", defaultValue: true },
        { name: "enableWebPageSchema", type: "checkbox", defaultValue: true },
        { name: "enableBreadcrumbSchema", type: "checkbox", defaultValue: true },
        { name: "enableArticleSchema", type: "checkbox", defaultValue: true },
        { name: "additionalSchema", label: "Additional verified JSON-LD node", type: "json", localized: true, admin: { description: "Advanced. Optional schema.org object with @type. Never add claims, ratings, or awards without evidence." } },
      ] },
      { label: "Crawlers and verification", fields: [
        { name: "robotsAdditionalRules", label: "Additional robots.txt rules", type: "textarea", admin: { description: "Admin and API paths remain blocked regardless of these rules." } },
        { name: "googleVerification", type: "text" },
        { name: "bingVerification", type: "text" },
        { name: "yandexVerification", type: "text" },
      ] },
    ] },
  ],
  versions: { drafts: { autosave: true } },
};
