import type { Locale } from "@/content/home";

export type CareerJob = {
  id: string;
  title: string;
  detailTitle: string;
  location: string;
  summary: string;
  overview: string;
  responsibilities: string[];
  requirements: string[];
  category?: string;
  tags?: string[];
  employmentType?: string;
  city?: string;
};

type WorkplacePoint = { title: string; body: string; target: string };

export type CareersContent = {
  hero: { lead: string; title: string; body: string };
  investing: { label: string; title: string; body: string };
  workplace: { label: string; title: string; body: string; targetLabel: string; points: WorkplacePoint[] };
  opportunities: { title: string; body: string; details: string };
  jobs: CareerJob[];
  talent: { label: string; title: string; body: string; formTitle: string; fields: string[]; submit: string };
  detail: { overview: string; responsibilities: string; requirements: string; apply: string; fields: string[]; submit: string };
};

const en: CareersContent = {
  hero: {
    lead: "Ambition Begins with People",
    title: "Because extraordinary achievements are driven by extraordinary talent",
    body: "We attract innovators, talented professionals, and exceptional individuals who share our ambition to create lasting impact and help shape the future.",
  },
  investing: {
    label: "Investing in Talent",
    title: "Startime... A Hub for Innovation and Creativity",
    body: "At Startime, we recognize that human capital is the most important enabler of achieving our vision and shaping our future. That is why we are committed to attracting innovators, talented individuals, and exceptional professionals who share our ambition, while providing a professional environment that empowers them to grow, innovate, and contribute to projects and initiatives that create sustainable economic, knowledge-based, and societal impact.",
  },
  workplace: {
    label: "Work Environment",
    title: "Sharpening Knowledge... Empowering Creativity",
    body: "At Startime, we believe that an inspiring professional environment is the foundation where ideas emerge, talent thrives, and ambition is transformed into achievement. That is why we are committed to fostering a workplace culture that attracts exceptional talent, empowers continuous growth and innovation, and enables individuals to contribute to projects and initiatives that create sustainable economic, knowledge-driven, and societal impact.",
    targetLabel: "2030 Target:",
    points: [
      { title: "Professional Development", body: "We provide continuous learning and professional development pathways that strengthen talent readiness, enabling individuals to navigate future transformations and lead growth.", target: "+10,000 annual training and professional development hours" },
      { title: "Innovation", body: "We encourage new ideas and support their transformation into initiatives and solutions that advance business development and create sustainable value.", target: "+50 innovation initiatives and implementable ideas" },
      { title: "Empowerment", body: "We foster a culture of trust and accountability, empowering qualified talent to lead change, contribute to decision-making, and drive results.", target: "70% of leadership positions held by national talent" },
      { title: "Creating Impact", body: "We connect performance with value creation and measure success through the impact generated by the projects and initiatives our people help deliver.", target: "100% of employees engaged in projects and initiatives with measurable impact" },
      { title: "Career Growth", body: "We provide clear career pathways that offer continuous opportunities for advancement, professional development, and the achievement of long-term career aspirations.", target: "90% retention rate among exceptional talent and high performers" },
      { title: "Inspiring Workplace", body: "We cultivate a workplace culture built on collaboration, respect, recognition, continuous learning, and a shared commitment to excellence.", target: "95% employee satisfaction rate with the work environment" },
    ],
  },
  opportunities: {
    title: "Career Opportunities",
    body: "At Startime, we offer diverse career opportunities for ambitious professionals seeking to contribute to the development of projects, initiatives, and platforms that create value and generate meaningful impact.",
    details: "View Details & Apply",
  },
  jobs: [
    {
      id: "3d-designer", title: "3D Designer", detailTitle: "3D Designer", location: "Riyadh | Full-Time",
      summary: "Contribute to the design and development of three-dimensional visual models and creative assets for specialized projects, platforms, and exhibitions, enhancing visual experiences and elevating project deliverables through the highest standards of creativity and professional excellence.",
      overview: "Contribute to the design and development of three-dimensional visual models and creative assets for specialized projects, platforms, and exhibitions, enhancing visual experiences and elevating project deliverables through the highest standards of creativity and professional excellence.",
      responsibilities: [
        "Develop 3D models, visual assets, and design concepts for projects and initiatives.",
        "Create professional visualizations, renderings, and presentation materials.",
        "Collaborate with creative and production teams to develop innovative design solutions.",
        "Ensure all deliverables align with approved visual identity standards and technical requirements.",
        "Support the development of design concepts and transform creative ideas into executable models.",
      ],
      requirements: [
        "Bachelor’s degree in Engineering Design, 3D Design, or a related discipline.",
        "Demonstrated experience in designing and developing 3D visual models and creative assets.",
        "Proficiency in industry-standard 3D design and modeling software.",
        "A professional portfolio showcasing the quality of previous work and relevant experience.",
        "Ability to develop innovative design solutions that meet project objectives and technical standards.",
        "Strong communication skills and the ability to work effectively within multidisciplinary teams.",
        "High attention to detail and commitment to quality and execution excellence.",
      ],
    },
    {
      id: "creative-director", title: "Creative Director", detailTitle: "Creative Director", location: "Riyadh | Full-Time",
      summary: "Lead the creative direction of projects and initiatives while developing innovative concepts and experiences that strengthen brand identity, enrich audience engagement, and transform strategic vision into impactful outcomes.",
      overview: "The Creative Director leads the development of the creative vision for projects, platforms, and specialized events, overseeing the transformation of strategic ideas and objectives into innovative concepts and experiences that reflect Startime’s identity, support project goals, and maximize their impact.",
      responsibilities: [
        "Lead and develop the creative direction of projects and strategic initiatives.",
        "Oversee the development of creative concepts, visual solutions, and immersive experiences.",
        "Manage creative teams and ensure the quality, consistency, and effectiveness of all deliverables.",
        "Develop ideas and initiatives that enhance value creation and strengthen competitive differentiation.",
        "Collaborate with departments and stakeholders to align creative vision with strategic objectives.",
        "Drive innovation across projects while maintaining alignment with brand and business goals.",
      ],
      requirements: [
        "Bachelor’s degree in Design, Media, Marketing, Communications, or a related field.",
        "Proven professional experience in leading creative projects and managing multidisciplinary creative teams.",
        "A strong portfolio demonstrating the ability to develop impactful concepts, campaigns, and creative experiences.",
        "Advanced understanding of branding, audience engagement, and visual communication.",
        "Ability to translate strategic direction into innovative and executable creative solutions.",
        "Strong leadership, communication, and stakeholder management skills.",
        "Ability to manage multiple projects and priorities within a dynamic work environment.",
      ],
    },
    {
      id: "events-coordinator", title: "Events Coordinator", detailTitle: "Events Coordinator", location: "Riyadh | Full-Time",
      summary: "Support the planning, coordination, and execution of business events and specialized exhibitions, ensuring seamless operational delivery, exceptional stakeholder experiences, and successful project outcomes aligned with the highest standards of quality and execution.",
      overview: "The Events Coordinator supports the planning, coordination, and execution of projects and business events, working closely with internal teams, partners, and service providers to ensure efficient operations and the successful achievement of project objectives and event deliverables.",
      responsibilities: [
        "Coordinate operational and organizational activities related to events and projects.",
        "Monitor timelines and execution plans to ensure timely and effective delivery.",
        "Liaise with suppliers, partners, and relevant stakeholders throughout project lifecycles.",
        "Support project teams during planning, execution, and closure phases.",
        "Prepare operational reports, track progress, and document project outcomes.",
        "Contribute to maintaining execution quality and enhancing participant and stakeholder experiences.",
      ],
      requirements: [
        "Bachelor’s degree in Business Administration or a related discipline.",
        "Proven experience in coordinating and managing business events or projects.",
        "Strong organizational, prioritization, and follow-up skills.",
        "Ability to thrive in a fast-paced and dynamic work environment.",
        "Excellent communication and coordination skills with diverse stakeholders.",
        "Proficiency in project management software and productivity tools.",
      ],
    },
    {
      id: "web-ui-ux-designer", title: "Web UX\\UI Designer", detailTitle: "Web UI\\UX Designer", location: "Riyadh | Full-Time",
      summary: "Contribute to the design and development of modern digital interfaces that enhance user experience and translate corporate identity into integrated digital journeys, supporting platform objectives and elevating user engagement.",
      overview: "The Web UI\\UX Designer is responsible for developing visual concepts and interface designs for websites and digital platforms, creating engaging and intuitive user experiences that combine visual excellence with usability, while ensuring the highest standards of user experience and digital brand consistency.",
      responsibilities: [
        "Design user interfaces for websites, digital platforms, and web-based applications.",
        "Develop wireframes, user flows, and high-fidelity design prototypes.",
        "Enhance user experience by improving usability, accessibility, and user interaction.",
        "Ensure consistency across designs in alignment with approved visual identity and digital standards.",
        "Collaborate with development, content, and marketing teams to transform concepts into seamless digital experiences.",
        "Stay current with emerging UI/UX trends and implement industry best practices.",
      ],
      requirements: [
        "Bachelor’s degree in User Interface Design, Digital Design, or a related field.",
        "Proven professional experience in designing websites and digital platforms.",
        "Proficiency in industry-standard design tools such as Figma, Adobe XD, or equivalent platforms.",
        "Strong understanding of UI/UX principles, user behavior, and user-centered design methodologies.",
        "A professional portfolio demonstrating the quality of completed digital products and user experiences.",
        "Ability to translate business requirements and strategic objectives into intuitive and engaging digital experiences.",
        "Strong creative thinking, innovation, and attention to detail.",
      ],
    },
  ],
  talent: {
    label: "Startime Talent Acquisition Program",
    title: "Continuously Seeking Professionals and Innovators",
    body: "At Startime, we recognize that exceptional talent deserves to be part of a professional network that values ambition, innovation, and impact. While the right opportunity may not be available today, we welcome innovators, talented professionals, and experienced specialists to join Startime’s Professional Network. We will connect with you when opportunities become available that align with your expertise, experience, and professional aspirations.",
    formTitle: "Join Our Professional Network",
    fields: ["Full Name*", "Email Address*", "Mobile Number*", "City", "Area of Expertise*", "Years of Experience", "CV*", "Additional Attachments", "Personal Statement"],
    submit: "Join Now",
  },
  detail: {
    overview: "Job Overview", responsibilities: "Key Responsibilities", requirements: "Employment Requirements", apply: "Apply for This Position",
    fields: ["Full Name*", "Email Address*", "Mobile Number*", "CV*", "Additional Attachments", "Professional Summary"],
    submit: "Submit Application",
  },
};

const ar: CareersContent = {
  hero: {
    lead: "الطموح يبدأ من الإنسان",
    title: "لأن أعظم الإنجازات تُبنى بكفاءات استثنائية",
    body: "نستقطب المواهب والكفاءات القادرة على صناعة الأثر وقيادة المستقبل.",
  },
  investing: {
    label: "نستثمر في العقول",
    title: "ستارتايم... حاضنة الابتكار والإبداع",
    body: "ندرك تماماً بأن رأس المال البشري هو الممكن الأهم لتحقيق رؤيتنا وصناعة مستقبلنا؛ ولذلك نسعى إلى استقطاب المبتكرين والموهوبين والكفاءات التي تشاركنا الطموح، ونوفر لهم بيئة مهنية تمكنهم من النمو والابتكار والمساهمة في بناء مشاريع ومبادرات ذات أثر اقتصادي ومعرفي ومجتمعي مستدام.",
  },
  workplace: {
    label: "بيئة العمل",
    title: "نصقل المعرفة... ونمكن الإبداع",
    body: "في ستارتايم، نؤمن بأن البيئة المهنية الملهمة هي الأساس الذي تنطلق منه الأفكار، وتنمو فيه المواهب، وتتحول من خلاله الطموحات إلى إنجازات. ولذلك نحرص على بناء ثقافة عمل تستقطب الكفاءات الاستثنائية وتمكنها من النمو والابتكار والمساهمة في مشاريع ومبادرات ذات أثر اقتصادي ومعرفي ومجتمعي مستدام.",
    targetLabel: "مستهدف 2030:",
    points: [
      { title: "التطوير المهني", body: "نوفر مسارات مستمرة للتعلم والتطوير المهني، بما يعزز جاهزية الكفاءات لمواكبة التحولات المستقبلية وقيادة النمو.", target: "+10000 ألف ساعة تدريب وتطوير مهني سنويًا" },
      { title: "الابتكار", body: "نشجع الأفكار الجديدة وندعم تحويلها إلى مبادرات وحلول تساهم في تطوير الأعمال وخلق قيمة مستدامة.", target: "+500 مبادرة ابتكارية وأفكار قابلة للتطبيق" },
      { title: "التمكين", body: "نمنح الثقة والمسؤولية للكفاءات المؤهلة لقيادة التغيير والمشاركة في صناعة القرار وتحقيق النتائج.", target: "70% من المناصب القيادية تُدار بكفاءات وطنية" },
      { title: "صناعة الأثر", body: "نربط الأداء بالقيمة المضافة، ونقيس النجاح بالأثر الذي تتركه المشاريع والمبادرات التي يساهم فيها فريق العمل.", target: "100% من الموظفين يشاركون في مشاريع ومبادرات ذات أثر قابل للقياس" },
      { title: "النمو الوظيفي", body: "نهيئ مسارات مهنية واضحة تتيح للكفاءات فرصًا مستمرة للتقدم والتطوير وتحقيق طموحاتها المهنية.", target: "90% معدل احتفاظ بالكفاءات الاستثنائية والمواهب" },
      { title: "بيئة محفزة", body: "نبني ثقافة عمل قائمة على التعاون والاحترام والتقدير والتعلم المستمر والسعي نحو التميز.", target: "95% مؤشر رضا الموظفين عن بيئة العمل" },
    ],
  },
  opportunities: {
    title: "فرص التوظيف",
    body: "في ستارتايم، نتيح فرصًا مهنية متنوعة للكفاءات الطموحة الراغبة في المشاركة في تطوير المشاريع والمبادرات والمنصات التي تسهم في بناء القيمة وصناعة الأثر.",
    details: "التفاصيل والتقديم",
  },
  jobs: [
    {
      id: "3d-designer", title: "مصمم هندسي", detailTitle: "مصمم هندسي ثلاثي الأبعاد", location: "الرياض | دوام كامل",
      summary: "المساهمة في تصميم وتطوير النماذج والعناصر البصرية ثلاثية الأبعاد للمشاريع والمنصات والمعارض المتخصصة، بما يعزز جودة التجربة البصرية ويرتقي بمخرجات المشاريع وفق أعلى معايير الإبداع والاحترافية.",
      overview: "المساهمة في تصميم وتطوير النماذج والعناصر البصرية ثلاثية الأبعاد للمشاريع والمنصات والمعارض المتخصصة، بما يعزز جودة التجربة البصرية ويرتقي بمخرجات المشاريع وفق أعلى معايير الإبداع والاحترافية.",
      responsibilities: [
        "تطوير النماذج والتصاميم ثلاثية الأبعاد للمشاريع والمبادرات.",
        "إعداد التصورات البصرية والعروض التقديمية الاحترافية.",
        "التعاون مع فرق الإبداع والإنتاج لتطوير الحلول الإبداعية.",
        "ضمان توافق المخرجات مع الهوية البصرية والمعايير الفنية المعتمدة.",
        "دعم تطوير المفاهيم التصميمية وتحويلها إلى نماذج قابلة للتنفيذ.",
      ],
      requirements: [
        "درجة البكالوريوس في التصميم الهندسي أو التصميم ثلاثي الأبعاد أو تخصص ذي صلة .",
        "خبرة عملية مثبتة في تصميم وتطوير النماذج والعناصر البصرية ثلاثية الأبعاد .",
        "إجادة برامج التصميم والنمذجة ثلاثية الأبعاد ذات العلاقة .",
        "تقديم محفظة أعمال احترافية (Portfolio) تعكس جودة الأعمال والخبرات السابقة .",
        "القدرة على تطوير حلول تصميمية مبتكرة تتوافق مع متطلبات المشاريع والمعايير الفنية .",
        "مهارات عالية في التواصل والعمل ضمن فرق متعددة التخصصات .",
        "الاهتمام بالتفاصيل والالتزام بمعايير الجودة والتنفيذ.",
      ],
    },
    {
      id: "creative-director", title: "مدير الإبداع", detailTitle: "مدير الإبداع", location: "الرياض | دوام كامل",
      summary: "قيادة التوجه الإبداعي للمشاريع والمبادرات، وتطوير مفاهيم وتجارب مبتكرة تسهم في تعزيز الهوية المؤسسية، وإثراء تجربة الجمهور، وتحويل الرؤى الاستراتيجية إلى أعمال ومخرجات ذات أثر ملموس.",
      overview: "يقود مدير الإبداع تطوير الرؤية الإبداعية للمشاريع والمنصات والفعاليات المتخصصة، ويشرف على تحويل الأفكار والتوجهات الاستراتيجية إلى مفاهيم وتجارب مبتكرة تعكس هوية ستارتايم وتسهم في تحقيق مستهدفات المشاريع وتعزيز أثرها.",
      responsibilities: [
        "قيادة وتطوير التوجه الإبداعي للمشاريع والمبادرات.",
        "الإشراف على تطوير المفاهيم الإبداعية والحلول البصرية والتجارب التفاعلية.",
        "إدارة الفرق الإبداعية وضمان جودة المخرجات واتساقها مع هوية المشروع.",
        "تطوير الأفكار والمبادرات التي تعزز القيمة المضافة والتميز التنافسي.",
        "التعاون مع مختلف الأقسام والدوائر لضمان التكامل بين الرؤية الإبداعية والأهداف الاستراتيجية.",
      ],
      requirements: [
        "بكالوريوس في التصميم أو الإعلام أو التسويق أو تخصص ذي صلة.",
        "خبرة مهنية مثبتة في قيادة وإدارة المشاريع والفرق الإبداعية.",
        "سجل أعمال يعكس القدرة على تطوير مفاهيم وحملات وتجارب إبداعية مؤثرة.",
        "فهم متقدم للعلامات التجارية وتجربة الجمهور والاتصال البصري.",
        "القدرة على تحويل التوجهات الاستراتيجية إلى حلول ومخرجات إبداعية قابلة للتنفيذ.",
        "مهارات قيادية عالية وإدارة فعالة للفرق متعددة التخصصات.",
      ],
    },
    {
      id: "events-coordinator", title: "منسق فعاليات", detailTitle: "منسق فعاليات", location: "الرياض | دوام كامل",
      summary: "المساهمة في تخطيط وتنسيق وتنفيذ فعاليات الأعمال والمعارض المتخصصة، بما يضمن تكامل العمليات التشغيلية وتحقيق تجربة متميزة للمشاركين والرعاة، ودعم نجاح المشاريع وفق أعلى معايير الجودة والتنفيذ.",
      overview: "يتولى منسق الفعاليات دعم عمليات التخطيط والتنظيم والتنفيذ للمشاريع والفعاليات، والتنسيق مع الفرق الداخلية والشركاء والموردين لضمان سير الأعمال بكفاءة وتحقيق المستهدفات التشغيلية والتنظيمية للمشروع.",
      responsibilities: [
        "تنسيق الأعمال التشغيلية والتنظيمية المرتبطة بالفعاليات والمشاريع.",
        "متابعة الجداول الزمنية وخطط التنفيذ والتأكد من الالتزام بها.",
        "التنسيق مع الموردين والشركاء والجهات ذات العلاقة.",
        "دعم فرق المشروع خلال مراحل التخطيط والتنفيذ والإغلاق.",
        "إعداد التقارير والمتابعات التشغيلية وتوثيق مخرجات العمل.",
        "المساهمة في ضمان جودة التنفيذ وتحسين تجربة المشاركين.",
      ],
      requirements: [
        "بكالوريوس في إدارة الأعمال أو تخصص ذي صلة.",
        "خبرة عملية في تنسيق وإدارة فعاليات الأعمال أو المشاريع.",
        "مهارات عالية في التنظيم وإدارة الأولويات والمتابعة.",
        "القدرة على العمل ضمن بيئة عمل سريعة ومتعددة المهام.",
        "مهارات تواصل وتنسيق فعالة مع مختلف الجهات ذات العلاقة.",
        "إجادة العمل على برامج إدارة المشاريع.",
      ],
    },
    {
      id: "web-ui-ux-designer", title: "مصمم واجهات ويب", detailTitle: "مصمم واجهات ويب", location: "الرياض | دوام كامل",
      summary: "المساهمة في تصميم وتطوير واجهات رقمية عصرية تعزز تجربة المستخدم وتترجم الهوية المؤسسية إلى تجارب رقمية متكاملة، بما يدعم تحقيق أهداف المنصات والمواقع الرقمية ويرتقي بجودة التفاعل مع المستخدمين.",
      overview: "يتولى مصمم واجهات الويب تطوير التصاميم والمفاهيم البصرية للمواقع والمنصات الرقمية، والعمل على بناء تجارب استخدام فعالة وجذابة تجمع بين الجمال البصري وسهولة الاستخدام، بما يضمن تحقيق أفضل المعايير في تجربة المستخدم والهوية الرقمية.",
      responsibilities: [
        "تصميم واجهات المستخدم للمواقع والمنصات والتطبيقات الرقمية.",
        "تطوير النماذج الأولية (Wireframes) والتصاميم النهائية عالية الدقة.",
        "تحسين تجربة المستخدم ورفع كفاءة التفاعل وسهولة الاستخدام.",
        "ضمان اتساق التصاميم مع الهوية البصرية والمعايير الرقمية المعتمدة.",
        "التعاون مع فرق التطوير والمحتوى والتسويق لتحويل التصاميم إلى تجارب رقمية متكاملة.",
        "متابعة التوجهات الحديثة في تصميم وتجربة المستخدم وتطبيق أفضل الممارسات.",
      ],
      requirements: [
        "بكالوريوس في تصميم واجهات المستخدم أو أحد التخصصات ذات العلاقة.",
        "خبرة عملية مثبتة في تصميم المواقع والمنصات الرقمية.",
        "إتقان أدوات التصميم الاحترافية مثل Figma و Adobe XD أو ما يعادلها.",
        "فهم متقدم لمبادئ UI/UX وتجربة وسلوك المستخدم.",
        "محفظة أعمال احترافية (Portfolio) تعكس جودة المشاريع والتجارب الرقمية المنفذة.",
        "القدرة على تحويل المتطلبات والأهداف التجارية إلى تجارب رقمية فعالة وجذابة.",
        "مهارات عالية في الابتكار والتفكير التصميمي والاهتمام بالتفاصيل.",
      ],
    },
  ],
  talent: {
    label: "برنامج ستارتايم للاستقطاب",
    title: "نبحث باستمرار عن المحترفين والمبتكرين",
    body: "قد لا تكون الفرصة المناسبة لك متاحة اليوم، لكننا ندرك بأن الكفاءات الاستثنائية تستحق أن تكون جزءًا من شبكتنا المهنية؛ لذا نرحب بانضمام المبتكرين والموهوبين وأصحاب الخبرات النوعية إلى قاعدة المواهب في ستارتايم، وسنتواصل معكم عند توفر الفرص التي تتوافق مع خبراتكم وتطلعاتكم المهنية.",
    formTitle: "انضم إلى شبكتنا الاحترافية",
    fields: ["الاسم الكامل*", "البريد الإلكتروني*", "رقم الجوال*", "المدينة", "مجال التخصص*", "سنوات الخبرة", "السيرة الذاتية*", "المرفقات الإضافية", "رسالة تعريفية"],
    submit: "انضم الآن",
  },
  detail: {
    overview: "نبذة عن الوظيفة", responsibilities: "المسؤوليات الرئيسية", requirements: "متطلبات التوظيف", apply: "التقديم على الوظيفة",
    fields: ["الاسم الكامل*", "البريد الإلكتروني*", "رقم الجوال*", "السيرة الذاتية*", "المرفقات الإضافية", "نبذة تعريفية"],
    submit: "قدم الآن",
  },
};

export const careersContent: Record<Locale, CareersContent> = { en, ar };
