import { sql, type MigrateUpArgs, type MigrateDownArgs } from "@payloadcms/db-sqlite";

/** Additive only; does not update page content, media, or existing settings. */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.run(sql`CREATE TABLE IF NOT EXISTS \`icon_settings\` (
    \`id\` integer PRIMARY KEY NOT NULL,
    \`content_mobile_width\` numeric,
    \`content_mobile_height\` numeric,
    \`content_tablet_width\` numeric,
    \`content_tablet_height\` numeric,
    \`content_laptop_width\` numeric,
    \`content_laptop_height\` numeric,
    \`content_desktop_width\` numeric,
    \`content_desktop_height\` numeric,
    \`content_imac_width\` numeric,
    \`content_imac_height\` numeric,
    \`actions_mobile_width\` numeric,
    \`actions_mobile_height\` numeric,
    \`actions_tablet_width\` numeric,
    \`actions_tablet_height\` numeric,
    \`actions_laptop_width\` numeric,
    \`actions_laptop_height\` numeric,
    \`actions_desktop_width\` numeric,
    \`actions_desktop_height\` numeric,
    \`actions_imac_width\` numeric,
    \`actions_imac_height\` numeric,
    \`carousel_mobile_width\` numeric,
    \`carousel_mobile_height\` numeric,
    \`carousel_tablet_width\` numeric,
    \`carousel_tablet_height\` numeric,
    \`carousel_laptop_width\` numeric,
    \`carousel_laptop_height\` numeric,
    \`carousel_desktop_width\` numeric,
    \`carousel_desktop_height\` numeric,
    \`carousel_imac_width\` numeric,
    \`carousel_imac_height\` numeric,
    \`social_mobile_width\` numeric,
    \`social_mobile_height\` numeric,
    \`social_tablet_width\` numeric,
    \`social_tablet_height\` numeric,
    \`social_laptop_width\` numeric,
    \`social_laptop_height\` numeric,
    \`social_desktop_width\` numeric,
    \`social_desktop_height\` numeric,
    \`social_imac_width\` numeric,
    \`social_imac_height\` numeric,
    \`contact_mobile_width\` numeric,
    \`contact_mobile_height\` numeric,
    \`contact_tablet_width\` numeric,
    \`contact_tablet_height\` numeric,
    \`contact_laptop_width\` numeric,
    \`contact_laptop_height\` numeric,
    \`contact_desktop_width\` numeric,
    \`contact_desktop_height\` numeric,
    \`contact_imac_width\` numeric,
    \`contact_imac_height\` numeric,
    \`forms_mobile_width\` numeric,
    \`forms_mobile_height\` numeric,
    \`forms_tablet_width\` numeric,
    \`forms_tablet_height\` numeric,
    \`forms_laptop_width\` numeric,
    \`forms_laptop_height\` numeric,
    \`forms_desktop_width\` numeric,
    \`forms_desktop_height\` numeric,
    \`forms_imac_width\` numeric,
    \`forms_imac_height\` numeric,
    \`menu_mobile_width\` numeric,
    \`menu_mobile_height\` numeric,
    \`menu_tablet_width\` numeric,
    \`menu_tablet_height\` numeric,
    \`menu_laptop_width\` numeric,
    \`menu_laptop_height\` numeric,
    \`menu_desktop_width\` numeric,
    \`menu_desktop_height\` numeric,
    \`menu_imac_width\` numeric,
    \`menu_imac_height\` numeric,
    \`updated_at\` text,
    \`created_at\` text
  );`);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP TABLE IF EXISTS \`icon_settings\`;`);
}
